"""Add status to trailer

Revision ID: 32be0878bf48
Revises: 2d1c7940f8fe
Create Date: 2024-11-26 22:08:19.778072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be0878bf48'
down_revision: Union[str, None] = '2d1c7940f8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailer', sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'UNAVAILABLE', name='trailerstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trailer', 'status')
    # ### end Alembic commands ###
