"""Add TrailerImage model and relation to Trailer

Revision ID: e5fba50db8f2
Revises: 558b7c2fcac3
Create Date: 2024-11-27 23:12:45.194267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fba50db8f2'
down_revision: Union[str, None] = '558b7c2fcac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
